/**
 * Full production-mode verification.
 *
 * Runs every browser suite against a real production build served by `next start`, instead
 * of against the dev server. This matters: two defects (unknown posts returning 500, and
 * localhost links in the production sitemap) were ONLY visible in a production build — the
 * dev server and the prerendered HTML both looked fine.
 *
 * Sequence:
 *   1. require the local content API (the offline build reads content through it)
 *   2. build in production mode (`build:local`, i.e. a production client + `next build`)
 *   3. stop anything on the site port, start `next start`
 *   4. run the browser suites against it
 *   5. shut the server down
 *
 * The admin/editor suites run against an admin built for the LOCAL content API, so this
 * verifies production *rendering*. Verifying the editor against TinaCloud requires real
 * credentials (see DEPLOYMENT.md) — the build refuses to run without them, by design.
 *
 * Prerequisite: the local content API must be running in another terminal (`npx tinacms dev`
 * or `npm run dev` leaves it on port 4001).
 *
 * Usage: node scripts/verify-prod.mjs [port]
 */
import { spawn, spawnSync } from 'node:child_process';
import { join } from 'node:path';

const PORT = Number(process.argv[2] ?? 3000);
const BASE_URL = `http://localhost:${PORT}`;
const API_URL = process.env.TINA_LOCAL_URL ?? 'http://localhost:4001/graphql';

const run = (command, args, options = {}) =>
  spawnSync(command, args, { stdio: 'inherit', shell: process.platform === 'win32', ...options });

const step = (title) => console.log(`\n${'─'.repeat(72)}\n${title}\n${'─'.repeat(72)}`);

async function apiReachable() {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ query: '{ postConnection { totalCount } }' }),
      signal: AbortSignal.timeout(5000),
    });
    return response.ok;
  } catch {
    return false;
  }
}

async function waitForServer(timeoutMs = 90_000) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      // Any HTTP response means the server is up; the status itself is asserted by the suite.
      await fetch(`${BASE_URL}/`, { signal: AbortSignal.timeout(3000) });
      return true;
    } catch {
      await new Promise((resolve) => setTimeout(resolve, 1500));
    }
  }
  return false;
}

const failures = [];
let server;

try {
  // 1. local content API -----------------------------------------------------
  step('1. Checking the local content API');
  if (!(await apiReachable())) {
    console.error(
      `✖ The local content API is not reachable at ${API_URL}.\n` +
        '  Start it in another terminal: npx tinacms dev\n' +
        '  (the production client is generated by the local build, which reads from it)'
    );
    process.exit(1);
  }
  console.log(`✔ Content API reachable at ${API_URL}`);

  // 2. production build ------------------------------------------------------
  step('2. Building in production mode');
  const build = run('node', ['scripts/build-local.mjs']);
  if (build.status !== 0) {
    console.error('\n✖ Production build failed.');
    process.exit(build.status ?? 1);
  }

  // 3. production server -----------------------------------------------------
  step(`3. Starting the production server on port ${PORT}`);
  // Spawned WITHOUT a shell so that kill() reaches the actual Next.js process. With
  // `shell: true` on Windows, kill() only terminates the wrapping shell and the server keeps
  // holding the port, which leaves this script hanging at exit.
  const nextBin = join('node_modules', 'next', 'dist', 'bin', 'next');
  server = spawn(process.execPath, [nextBin, 'start', '-p', String(PORT)], {
    stdio: 'inherit',
    env: { ...process.env, PORT: String(PORT) },
  });
  server.on('error', (error) => console.error(`server process error: ${error.message}`));

  if (!(await waitForServer())) {
    console.error(`\n✖ The production server did not respond on ${BASE_URL}.`);
    process.exit(1);
  }
  console.log(`✔ Production server ready at ${BASE_URL}`);

  // 4. suites ----------------------------------------------------------------
  const suites = [
    { name: 'http statuses', args: ['scripts/http-status-smoke.mjs', BASE_URL] },
    { name: 'published-page interactions', args: ['scripts/interaction-smoke.mjs', BASE_URL] },
    { name: 'visual editing', args: ['scripts/visual-edit-smoke.mjs', BASE_URL] },
    { name: 'editor (admin)', args: ['scripts/admin-smoke.mjs', BASE_URL] },
    { name: 'editor save', args: ['scripts/save-smoke.mjs', BASE_URL] },
  ];

  for (const suite of suites) {
    step(`4. Running suite: ${suite.name}`);
    const result = run('node', suite.args);
    if (result.status !== 0) failures.push(suite.name);
  }
} catch (error) {
  console.error(`\n✖ verify-prod failed: ${error.message}`);
  failures.push('verify-prod');
} finally {
  // 5. shutdown --------------------------------------------------------------
  if (server?.pid) {
    console.log('\nShutting down the production server...');
    if (process.platform === 'win32') {
      // Kill the whole tree so nothing keeps the port bound.
      spawnSync('taskkill', ['/pid', String(server.pid), '/T', '/F'], { stdio: 'ignore' });
    } else {
      server.kill('SIGTERM');
    }
  }
}

step('Summary');
if (failures.length === 0) {
  console.log('✔ All suites passed against the production build.');
  process.exit(0);
}
console.log(`✖ Failing suites: ${failures.join(', ')}`);
process.exit(1);
